import type { PersonSeed, SportsDataConfidence, SportsLeagueKey, SportsPersonRole } from './types';

/**
 * First-party people registry for figures material to BB Sports coverage.
 *
 * NOT a scraped career-stats encyclopedia. Each record stores identity, role,
 * team association, a short BB Sports summary, and a source citation.
 * No proprietary season stats tables are stored.
 *
 * Verified: 2026-07-15 against club official sites linked per row.
 * Coaching titles change — prefer FLAGGED when tenure is season-sensitive.
 */

function person(input: {
  personKey: string;
  fullName: string;
  commonName?: string;
  role: SportsPersonRole;
  leagueKey: SportsLeagueKey;
  teamKey: string;
  positionOrTitle: string;
  summary: string;
  officialUrl: string;
  dataSource: string;
  dataConfidence?: SportsDataConfidence;
  dataNotes?: string;
}): PersonSeed {
  return Object.freeze({
    personKey: input.personKey,
    fullName: input.fullName,
    commonName: input.commonName ?? input.fullName,
    role: input.role,
    leagueKey: input.leagueKey,
    teamKey: input.teamKey,
    positionOrTitle: input.positionOrTitle,
    summary: input.summary,
    officialUrl: input.officialUrl,
    dataSource: input.dataSource,
    dataSourceUrl: input.officialUrl,
    dataConfidence: input.dataConfidence ?? 'CROSS_REFERENCED',
    dataNotes:
      input.dataNotes ??
      'Identity/role only. No proprietary season stats table stored. Re-verify team association each offseason.',
  });
}

export const PERSON_SEEDS: readonly PersonSeed[] = Object.freeze([
  // ---------- NFL ----------
  person({
    personKey: 'caleb-williams',
    fullName: 'Caleb Williams',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Quarterback',
    summary: 'Chicago Bears quarterback and the central figure of Brad’s Bears franchise thesis.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'ben-johnson-bears',
    fullName: 'Ben Johnson',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Head coach',
    summary: 'Bears head coach material to BB Sports Bears coverage.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Coaching tenures change. Confirm active title on Bears.com before treating as current.',
  }),
  person({
    personKey: 'patrick-mahomes',
    fullName: 'Patrick Mahomes',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'kansas-city-chiefs',
    positionOrTitle: 'Quarterback',
    summary: 'Chiefs quarterback and the standard every contender is measured against in BB Sports NFL copy.',
    officialUrl: 'https://www.chiefs.com/',
    dataSource: 'Kansas City Chiefs official site',
  }),
  person({
    personKey: 'andy-reid',
    fullName: 'Andy Reid',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'kansas-city-chiefs',
    positionOrTitle: 'Head coach',
    summary: 'Chiefs head coach; long-tenured reference point in BB Sports AFC coverage.',
    officialUrl: 'https://www.chiefs.com/',
    dataSource: 'Kansas City Chiefs official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'jalen-hurts',
    fullName: 'Jalen Hurts',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'philadelphia-eagles',
    positionOrTitle: 'Quarterback',
    summary: 'Eagles quarterback in BB Sports “real quarterback” franchise framing.',
    officialUrl: 'https://www.philadelphiaeagles.com/',
    dataSource: 'Philadelphia Eagles official site',
  }),
  person({
    personKey: 'josh-allen',
    fullName: 'Josh Allen',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'buffalo-bills',
    positionOrTitle: 'Quarterback',
    summary: 'Bills quarterback regularly cited as top-tier talent with roster questions around him.',
    officialUrl: 'https://www.buffalobills.com/',
    dataSource: 'Buffalo Bills official site',
  }),
  person({
    personKey: 'lamar-jackson',
    fullName: 'Lamar Jackson',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'baltimore-ravens',
    positionOrTitle: 'Quarterback',
    summary: 'Ravens quarterback central to BB Sports regular-season excellence vs January framing.',
    officialUrl: 'https://www.baltimoreravens.com/',
    dataSource: 'Baltimore Ravens official site',
  }),
  person({
    personKey: 'cj-stroud',
    fullName: 'C.J. Stroud',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'houston-texans',
    positionOrTitle: 'Quarterback',
    summary: 'Texans quarterback and young-QB climbing narrative in BB Sports rankings.',
    officialUrl: 'https://www.houstontexans.com/',
    dataSource: 'Houston Texans official site',
  }),
  person({
    personKey: 'jordan-love',
    fullName: 'Jordan Love',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'green-bay-packers',
    positionOrTitle: 'Quarterback',
    summary: 'Packers quarterback referenced as a real deal with defense as the swing factor.',
    officialUrl: 'https://www.packers.com/',
    dataSource: 'Green Bay Packers official site',
  }),
  person({
    personKey: 'dak-prescott',
    fullName: 'Dak Prescott',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'dallas-cowboys',
    positionOrTitle: 'Quarterback',
    summary: 'Cowboys quarterback in BB Sports brand-vs-contention columns.',
    officialUrl: 'https://www.dallascowboys.com/',
    dataSource: 'Dallas Cowboys official site',
  }),
  person({
    personKey: 'mike-tomlin',
    fullName: 'Mike Tomlin',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'pittsburgh-steelers',
    positionOrTitle: 'Head coach',
    summary: 'Steelers head coach; BB Sports reference for floor/ceiling coaching identity.',
    officialUrl: 'https://www.steelers.com/',
    dataSource: 'Pittsburgh Steelers official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'matthew-stafford',
    fullName: 'Matthew Stafford',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-rams',
    positionOrTitle: 'Quarterback',
    summary: 'Rams quarterback in Stafford–McVay axis coverage.',
    officialUrl: 'https://www.therams.com/',
    dataSource: 'Los Angeles Rams official site',
  }),
  person({
    personKey: 'trevor-lawrence',
    fullName: 'Trevor Lawrence',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'jacksonville-jaguars',
    positionOrTitle: 'Quarterback',
    summary: 'Jaguars quarterback in BB Sports wasted-window framing.',
    officialUrl: 'https://www.jaguars.com/',
    dataSource: 'Jacksonville Jaguars official site',
  }),
  person({
    personKey: 'jayden-daniels',
    fullName: 'Jayden Daniels',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'washington-commanders',
    positionOrTitle: 'Quarterback',
    summary: 'Commanders quarterback called out as must-watch talent in rankings copy.',
    officialUrl: 'https://www.commanders.com/',
    dataSource: 'Washington Commanders official site',
  }),
  person({
    personKey: 'justin-herbert',
    fullName: 'Justin Herbert',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-chargers',
    positionOrTitle: 'Quarterback',
    summary: 'Chargers quarterback in Harbaugh-era BB Sports notes.',
    officialUrl: 'https://www.chargers.com/',
    dataSource: 'Los Angeles Chargers official site',
  }),
  person({
    personKey: 'joe-burrow',
    fullName: 'Joe Burrow',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'cincinnati-bengals',
    positionOrTitle: 'Quarterback',
    summary: 'Bengals quarterback; health is the recurring BB Sports swing variable.',
    officialUrl: 'https://www.bengals.com/',
    dataSource: 'Cincinnati Bengals official site',
  }),

  // ---------- MLB ----------
  person({
    personKey: 'aaron-judge',
    fullName: 'Aaron Judge',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-yankees',
    positionOrTitle: 'Outfielder',
    summary: 'Yankees star regularly referenced in BB Sports Yankees franchise criticism.',
    officialUrl: 'https://www.mlb.com/yankees',
    dataSource: 'MLB.com / Yankees club page',
  }),
  person({
    personKey: 'shohei-ohtani',
    fullName: 'Shohei Ohtani',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'los-angeles-dodgers',
    positionOrTitle: 'Two-way player',
    summary: 'Dodgers franchise centerpiece in BB Sports baseball coverage.',
    officialUrl: 'https://www.mlb.com/dodgers',
    dataSource: 'MLB.com / Dodgers club page',
  }),
  person({
    personKey: 'mookie-betts',
    fullName: 'Mookie Betts',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'los-angeles-dodgers',
    positionOrTitle: 'Infielder/outfielder',
    summary: 'Dodgers star and frequent payroll-dynasty reference in BB Sports columns.',
    officialUrl: 'https://www.mlb.com/dodgers',
    dataSource: 'MLB.com / Dodgers club page',
  }),
  person({
    personKey: 'bobby-witt-jr',
    fullName: 'Bobby Witt Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'kansas-city-royals',
    positionOrTitle: 'Shortstop',
    summary: 'Royals star framed as a top-tier talent outside the usual coastal conversation.',
    officialUrl: 'https://www.mlb.com/royals',
    dataSource: 'MLB.com / Royals club page',
  }),
  person({
    personKey: 'paul-skenes',
    fullName: 'Paul Skenes',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'pittsburgh-pirates',
    positionOrTitle: 'Pitcher',
    summary: 'Pirates ace used in BB Sports ownership-vs-talent framing.',
    officialUrl: 'https://www.mlb.com/pirates',
    dataSource: 'MLB.com / Pirates club page',
  }),
  person({
    personKey: 'elly-de-la-cruz',
    fullName: 'Elly De La Cruz',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'cincinnati-reds',
    positionOrTitle: 'Shortstop',
    summary: 'Reds star called must-watch TV in BB Sports rankings notes.',
    officialUrl: 'https://www.mlb.com/reds',
    dataSource: 'MLB.com / Reds club page',
  }),
  person({
    personKey: 'gunnar-henderson',
    fullName: 'Gunnar Henderson',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'baltimore-orioles',
    positionOrTitle: 'Infielder',
    summary: 'Orioles young-core figure in BB Sports cheap-talent-depth coverage.',
    officialUrl: 'https://www.mlb.com/orioles',
    dataSource: 'MLB.com / Orioles club page',
  }),
  person({
    personKey: 'ronald-acuna-jr',
    fullName: 'Ronald Acuña Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'atlanta-braves',
    positionOrTitle: 'Outfielder',
    summary: 'Braves star in BB Sports front-office excellence framing.',
    officialUrl: 'https://www.mlb.com/braves',
    dataSource: 'MLB.com / Braves club page',
  }),
  person({
    personKey: 'tarik-skubal',
    fullName: 'Tarik Skubal',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'detroit-tigers',
    positionOrTitle: 'Pitcher',
    summary: 'Tigers ace in BB Sports back-on-the-map pitching narrative.',
    officialUrl: 'https://www.mlb.com/tigers',
    dataSource: 'MLB.com / Tigers club page',
  }),
  person({
    personKey: 'juan-soto',
    fullName: 'Juan Soto',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-mets',
    positionOrTitle: 'Outfielder',
    summary: 'Mets star acquisition central to Cohen-era BB Sports notes. Re-verify club association annually.',
    officialUrl: 'https://www.mlb.com/mets',
    dataSource: 'MLB.com / Mets club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'High-profile free-agent movement risk. Confirm club page before treating as current.',
  }),

  // ---------- NHL ----------
  person({
    personKey: 'connor-mcdavid',
    fullName: 'Connor McDavid',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'edmonton-oilers',
    positionOrTitle: 'Center',
    summary: 'Oilers captain and primary elite-skill reference in NHL rankings copy.',
    officialUrl: 'https://www.nhl.com/oilers',
    dataSource: 'NHL.com / Oilers club page',
  }),
  person({
    personKey: 'leon-draisaitl',
    fullName: 'Leon Draisaitl',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'edmonton-oilers',
    positionOrTitle: 'Center/winger',
    summary: 'Oilers co-star in McDavid–Draisaitl duo framing.',
    officialUrl: 'https://www.nhl.com/oilers',
    dataSource: 'NHL.com / Oilers club page',
  }),
  person({
    personKey: 'aleksander-barkov',
    fullName: 'Aleksander Barkov',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Center',
    summary: 'Florida Panthers captain; central to Brad’s disclosed Panthers bias coverage.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'matthew-tkachuk',
    fullName: 'Matthew Tkachuk',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Winger',
    summary: 'Panthers star forward in BB Sports Cup-era coverage.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'auston-matthews',
    fullName: 'Auston Matthews',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'toronto-maple-leafs',
    positionOrTitle: 'Center',
    summary: 'Maple Leafs star referenced in BB Sports Leafs window columns.',
    officialUrl: 'https://www.nhl.com/mapleleafs',
    dataSource: 'NHL.com / Maple Leafs club page',
  }),
  person({
    personKey: 'nathan-mackinnon',
    fullName: 'Nathan MacKinnon',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'colorado-avalanche',
    positionOrTitle: 'Center',
    summary: 'Avalanche star in MacKinnon–Makar core framing.',
    officialUrl: 'https://www.nhl.com/avalanche',
    dataSource: 'NHL.com / Avalanche club page',
  }),
  person({
    personKey: 'cale-makar',
    fullName: 'Cale Makar',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'colorado-avalanche',
    positionOrTitle: 'Defenseman',
    summary: 'Avalanche defenseman in elite-defense franchise notes.',
    officialUrl: 'https://www.nhl.com/avalanche',
    dataSource: 'NHL.com / Avalanche club page',
  }),
  person({
    personKey: 'connor-hellebuyck',
    fullName: 'Connor Hellebuyck',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'winnipeg-jets',
    positionOrTitle: 'Goaltender',
    summary: 'Jets goaltender in Presidents Trophy–era BB Sports notes.',
    officialUrl: 'https://www.nhl.com/jets',
    dataSource: 'NHL.com / Jets club page',
  }),
  person({
    personKey: 'alex-ovechkin',
    fullName: 'Alex Ovechkin',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'washington-capitals',
    positionOrTitle: 'Winger',
    summary: 'Capitals icon in record-chase coverage.',
    officialUrl: 'https://www.nhl.com/capitals',
    dataSource: 'NHL.com / Capitals club page',
  }),
  person({
    personKey: 'sidney-crosby',
    fullName: 'Sidney Crosby',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'pittsburgh-penguins',
    positionOrTitle: 'Center',
    summary: 'Penguins captain in late-window BB Sports framing.',
    officialUrl: 'https://www.nhl.com/penguins',
    dataSource: 'NHL.com / Penguins club page',
  }),
  person({
    personKey: 'kirill-kaprizov',
    fullName: 'Kirill Kaprizov',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'minnesota-wild',
    positionOrTitle: 'Winger',
    summary: 'Wild star in post-cap-hell supporting-cast notes.',
    officialUrl: 'https://www.nhl.com/wild',
    dataSource: 'NHL.com / Wild club page',
  }),

  // ---------- NBA ----------
  person({
    personKey: 'lebron-james',
    fullName: 'LeBron James',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'los-angeles-lakers',
    positionOrTitle: 'Forward',
    summary: 'Lakers franchise figure referenced in BB Sports Lakers criticism.',
    officialUrl: 'https://www.nba.com/lakers',
    dataSource: 'NBA.com / Lakers club page',
  }),
  person({
    personKey: 'stephen-curry',
    fullName: 'Stephen Curry',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'golden-state-warriors',
    positionOrTitle: 'Guard',
    summary: 'Warriors franchise figure central to BB Sports dynasty-era columns.',
    officialUrl: 'https://www.nba.com/warriors',
    dataSource: 'NBA.com / Warriors club page',
  }),
  person({
    personKey: 'nikola-jokic',
    fullName: 'Nikola Jokić',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'denver-nuggets',
    positionOrTitle: 'Center',
    summary: 'Nuggets franchise centerpiece in BB Sports NBA rankings framing.',
    officialUrl: 'https://www.nba.com/nuggets',
    dataSource: 'NBA.com / Nuggets club page',
  }),
  person({
    personKey: 'luka-doncic',
    fullName: 'Luka Dončić',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'dallas-mavericks',
    positionOrTitle: 'Guard',
    summary: 'Mavericks star in lethal halfcourt offense framing. Re-verify club association if trades occur.',
    officialUrl: 'https://www.nba.com/mavericks',
    dataSource: 'NBA.com / Mavericks club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'shai-gilgeous-alexander',
    fullName: 'Shai Gilgeous-Alexander',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'oklahoma-city-thunder',
    positionOrTitle: 'Guard',
    summary: 'Thunder star of the young-contender ranking thesis.',
    officialUrl: 'https://www.nba.com/thunder',
    dataSource: 'NBA.com / Thunder club page',
  }),
  person({
    personKey: 'jayson-tatum',
    fullName: 'Jayson Tatum',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'boston-celtics',
    positionOrTitle: 'Forward',
    summary: 'Celtics star in best-roster-construction ranking notes.',
    officialUrl: 'https://www.nba.com/celtics',
    dataSource: 'NBA.com / Celtics club page',
  }),
  person({
    personKey: 'anthony-edwards',
    fullName: 'Anthony Edwards',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'minnesota-timberwolves',
    positionOrTitle: 'Guard',
    summary: 'Timberwolves star in defense-first / double-team offense notes.',
    officialUrl: 'https://www.nba.com/timberwolves',
    dataSource: 'NBA.com / Timberwolves club page',
  }),
  person({
    personKey: 'joel-embiid',
    fullName: 'Joel Embiid',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'philadelphia-76ers',
    positionOrTitle: 'Center',
    summary: '76ers franchise health thesis in BB Sports rankings copy.',
    officialUrl: 'https://www.nba.com/sixers',
    dataSource: 'NBA.com / 76ers club page',
  }),
  person({
    personKey: 'giannis-antetokounmpo',
    fullName: 'Giannis Antetokounmpo',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'milwaukee-bucks',
    positionOrTitle: 'Forward',
    summary: 'Bucks franchise star in ceiling-vs-cap-hell framing.',
    officialUrl: 'https://www.nba.com/bucks',
    dataSource: 'NBA.com / Bucks club page',
  }),
  person({
    personKey: 'victor-wembanyama',
    fullName: 'Victor Wembanyama',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'san-antonio-spurs',
    positionOrTitle: 'Center/forward',
    summary: 'Spurs generational talent in must-watch rebuild notes.',
    officialUrl: 'https://www.nba.com/spurs',
    dataSource: 'NBA.com / Spurs club page',
  }),
  person({
    personKey: 'erik-spoelstra',
    fullName: 'Erik Spoelstra',
    role: 'head_coach',
    leagueKey: 'nba',
    teamKey: 'miami-heat',
    positionOrTitle: 'Head coach',
    summary: 'Long-tenured Heat head coach referenced in BB Sports Heat franchise notes.',
    officialUrl: 'https://www.nba.com/heat',
    dataSource: 'NBA.com / Heat club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'joe-mazulla',
    fullName: 'Joe Mazzulla',
    role: 'head_coach',
    leagueKey: 'nba',
    teamKey: 'boston-celtics',
    positionOrTitle: 'Head coach',
    summary: 'Celtics head coach in championship-roster construction era notes.',
    officialUrl: 'https://www.nba.com/celtics',
    dataSource: 'NBA.com / Celtics club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'ja-morant',
    fullName: 'Ja Morant',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'memphis-grizzlies',
    positionOrTitle: 'Guard',
    summary: 'Grizzlies star in healthy-core top-tier framing.',
    officialUrl: 'https://www.nba.com/grizzlies',
    dataSource: 'NBA.com / Grizzlies club page',
  }),
  person({
    personKey: 'paolo-banchero',
    fullName: 'Paolo Banchero',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'orlando-magic',
    positionOrTitle: 'Forward',
    summary: 'Magic young core figure with Wagner in BB Sports notes.',
    officialUrl: 'https://www.nba.com/magic',
    dataSource: 'NBA.com / Magic club page',
  }),
]);
