import type { PersonSeed, SportsDataConfidence, SportsLeagueKey, SportsPersonRole } from './types';

/**
 * First-party people registry for figures material to BB Sports coverage.
 *
 * NOT a scraped career-stats encyclopedia. Each record stores identity, role,
 * team association, a short BB Sports summary, and a source citation.
 * No proprietary season stats tables are stored.
 *
 * Verified: 2026-07-15 against club official sites linked per row.
 * Coaching titles change — prefer FLAGGED when tenure is season-sensitive.
 */

function person(input: {
  personKey: string;
  fullName: string;
  commonName?: string;
  role: SportsPersonRole;
  leagueKey: SportsLeagueKey;
  teamKey: string;
  positionOrTitle: string;
  summary: string;
  officialUrl: string;
  dataSource: string;
  dataConfidence?: SportsDataConfidence;
  dataNotes?: string;
}): PersonSeed {
  return Object.freeze({
    personKey: input.personKey,
    fullName: input.fullName,
    commonName: input.commonName ?? input.fullName,
    role: input.role,
    leagueKey: input.leagueKey,
    teamKey: input.teamKey,
    positionOrTitle: input.positionOrTitle,
    summary: input.summary,
    officialUrl: input.officialUrl,
    dataSource: input.dataSource,
    dataSourceUrl: input.officialUrl,
    dataConfidence: input.dataConfidence ?? 'CROSS_REFERENCED',
    dataNotes:
      input.dataNotes ??
      'Identity/role only. No proprietary season stats table stored. Re-verify team association each offseason.',
  });
}

export const PERSON_SEEDS: readonly PersonSeed[] = Object.freeze([
  // ---------- NFL ----------
  person({
    personKey: 'caleb-williams',
    fullName: 'Caleb Williams',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Quarterback',
    summary: 'Chicago Bears quarterback and the central figure of Brad’s Bears franchise thesis.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'ben-johnson-bears',
    fullName: 'Ben Johnson',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Head coach',
    summary: 'Bears head coach material to BB Sports Bears coverage.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Coaching tenures change. Confirm active title on Bears.com before treating as current.',
  }),
  person({
    personKey: 'patrick-mahomes',
    fullName: 'Patrick Mahomes',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'kansas-city-chiefs',
    positionOrTitle: 'Quarterback',
    summary: 'Chiefs quarterback and the standard every contender is measured against in BB Sports NFL copy.',
    officialUrl: 'https://www.chiefs.com/',
    dataSource: 'Kansas City Chiefs official site',
  }),
  person({
    personKey: 'andy-reid',
    fullName: 'Andy Reid',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'kansas-city-chiefs',
    positionOrTitle: 'Head coach',
    summary: 'Chiefs head coach; long-tenured reference point in BB Sports AFC coverage.',
    officialUrl: 'https://www.chiefs.com/',
    dataSource: 'Kansas City Chiefs official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'jalen-hurts',
    fullName: 'Jalen Hurts',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'philadelphia-eagles',
    positionOrTitle: 'Quarterback',
    summary: 'Eagles quarterback in BB Sports “real quarterback” franchise framing.',
    officialUrl: 'https://www.philadelphiaeagles.com/',
    dataSource: 'Philadelphia Eagles official site',
  }),
  person({
    personKey: 'josh-allen',
    fullName: 'Josh Allen',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'buffalo-bills',
    positionOrTitle: 'Quarterback',
    summary: 'Bills quarterback regularly cited as top-tier talent with roster questions around him.',
    officialUrl: 'https://www.buffalobills.com/',
    dataSource: 'Buffalo Bills official site',
  }),
  person({
    personKey: 'lamar-jackson',
    fullName: 'Lamar Jackson',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'baltimore-ravens',
    positionOrTitle: 'Quarterback',
    summary: 'Ravens quarterback central to BB Sports regular-season excellence vs January framing.',
    officialUrl: 'https://www.baltimoreravens.com/',
    dataSource: 'Baltimore Ravens official site',
  }),
  person({
    personKey: 'cj-stroud',
    fullName: 'C.J. Stroud',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'houston-texans',
    positionOrTitle: 'Quarterback',
    summary: 'Texans quarterback and young-QB climbing narrative in BB Sports rankings.',
    officialUrl: 'https://www.houstontexans.com/',
    dataSource: 'Houston Texans official site',
  }),
  person({
    personKey: 'jordan-love',
    fullName: 'Jordan Love',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'green-bay-packers',
    positionOrTitle: 'Quarterback',
    summary: 'Packers quarterback referenced as a real deal with defense as the swing factor.',
    officialUrl: 'https://www.packers.com/',
    dataSource: 'Green Bay Packers official site',
  }),
  person({
    personKey: 'dak-prescott',
    fullName: 'Dak Prescott',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'dallas-cowboys',
    positionOrTitle: 'Quarterback',
    summary: 'Cowboys quarterback in BB Sports brand-vs-contention columns.',
    officialUrl: 'https://www.dallascowboys.com/',
    dataSource: 'Dallas Cowboys official site',
  }),
  person({
    personKey: 'mike-tomlin',
    fullName: 'Mike Tomlin',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'pittsburgh-steelers',
    positionOrTitle: 'Head coach',
    summary: 'Steelers head coach; BB Sports reference for floor/ceiling coaching identity.',
    officialUrl: 'https://www.steelers.com/',
    dataSource: 'Pittsburgh Steelers official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'matthew-stafford',
    fullName: 'Matthew Stafford',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-rams',
    positionOrTitle: 'Quarterback',
    summary: 'Rams quarterback in Stafford–McVay axis coverage.',
    officialUrl: 'https://www.therams.com/',
    dataSource: 'Los Angeles Rams official site',
  }),
  person({
    personKey: 'trevor-lawrence',
    fullName: 'Trevor Lawrence',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'jacksonville-jaguars',
    positionOrTitle: 'Quarterback',
    summary: 'Jaguars quarterback in BB Sports wasted-window framing.',
    officialUrl: 'https://www.jaguars.com/',
    dataSource: 'Jacksonville Jaguars official site',
  }),
  person({
    personKey: 'jayden-daniels',
    fullName: 'Jayden Daniels',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'washington-commanders',
    positionOrTitle: 'Quarterback',
    summary: 'Commanders quarterback called out as must-watch talent in rankings copy.',
    officialUrl: 'https://www.commanders.com/',
    dataSource: 'Washington Commanders official site',
  }),
  person({
    personKey: 'justin-herbert',
    fullName: 'Justin Herbert',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-chargers',
    positionOrTitle: 'Quarterback',
    summary: 'Chargers quarterback in Harbaugh-era BB Sports notes.',
    officialUrl: 'https://www.chargers.com/',
    dataSource: 'Los Angeles Chargers official site',
  }),
  person({
    personKey: 'joe-burrow',
    fullName: 'Joe Burrow',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'cincinnati-bengals',
    positionOrTitle: 'Quarterback',
    summary: 'Bengals quarterback; health is the recurring BB Sports swing variable.',
    officialUrl: 'https://www.bengals.com/',
    dataSource: 'Cincinnati Bengals official site',
  }),

  // ---------- MLB ----------
  person({
    personKey: 'aaron-judge',
    fullName: 'Aaron Judge',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-yankees',
    positionOrTitle: 'Outfielder',
    summary: 'Yankees star regularly referenced in BB Sports Yankees franchise criticism.',
    officialUrl: 'https://www.mlb.com/yankees',
    dataSource: 'MLB.com / Yankees club page',
  }),
  person({
    personKey: 'shohei-ohtani',
    fullName: 'Shohei Ohtani',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'los-angeles-dodgers',
    positionOrTitle: 'Two-way player',
    summary: 'Dodgers franchise centerpiece in BB Sports baseball coverage.',
    officialUrl: 'https://www.mlb.com/dodgers',
    dataSource: 'MLB.com / Dodgers club page',
  }),
  person({
    personKey: 'mookie-betts',
    fullName: 'Mookie Betts',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'los-angeles-dodgers',
    positionOrTitle: 'Infielder/outfielder',
    summary: 'Dodgers star and frequent payroll-dynasty reference in BB Sports columns.',
    officialUrl: 'https://www.mlb.com/dodgers',
    dataSource: 'MLB.com / Dodgers club page',
  }),
  person({
    personKey: 'bobby-witt-jr',
    fullName: 'Bobby Witt Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'kansas-city-royals',
    positionOrTitle: 'Shortstop',
    summary: 'Royals star framed as a top-tier talent outside the usual coastal conversation.',
    officialUrl: 'https://www.mlb.com/royals',
    dataSource: 'MLB.com / Royals club page',
  }),
  person({
    personKey: 'paul-skenes',
    fullName: 'Paul Skenes',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'pittsburgh-pirates',
    positionOrTitle: 'Pitcher',
    summary: 'Pirates ace used in BB Sports ownership-vs-talent framing.',
    officialUrl: 'https://www.mlb.com/pirates',
    dataSource: 'MLB.com / Pirates club page',
  }),
  person({
    personKey: 'elly-de-la-cruz',
    fullName: 'Elly De La Cruz',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'cincinnati-reds',
    positionOrTitle: 'Shortstop',
    summary: 'Reds star called must-watch TV in BB Sports rankings notes.',
    officialUrl: 'https://www.mlb.com/reds',
    dataSource: 'MLB.com / Reds club page',
  }),
  person({
    personKey: 'gunnar-henderson',
    fullName: 'Gunnar Henderson',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'baltimore-orioles',
    positionOrTitle: 'Infielder',
    summary: 'Orioles young-core figure in BB Sports cheap-talent-depth coverage.',
    officialUrl: 'https://www.mlb.com/orioles',
    dataSource: 'MLB.com / Orioles club page',
  }),
  person({
    personKey: 'ronald-acuna-jr',
    fullName: 'Ronald Acuña Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'atlanta-braves',
    positionOrTitle: 'Outfielder',
    summary: 'Braves star in BB Sports front-office excellence framing.',
    officialUrl: 'https://www.mlb.com/braves',
    dataSource: 'MLB.com / Braves club page',
  }),
  person({
    personKey: 'tarik-skubal',
    fullName: 'Tarik Skubal',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'detroit-tigers',
    positionOrTitle: 'Pitcher',
    summary: 'Tigers ace in BB Sports back-on-the-map pitching narrative.',
    officialUrl: 'https://www.mlb.com/tigers',
    dataSource: 'MLB.com / Tigers club page',
  }),
  person({
    personKey: 'juan-soto',
    fullName: 'Juan Soto',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-mets',
    positionOrTitle: 'Outfielder',
    summary: 'Mets star acquisition central to Cohen-era BB Sports notes. Re-verify club association annually.',
    officialUrl: 'https://www.mlb.com/mets',
    dataSource: 'MLB.com / Mets club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'High-profile free-agent movement risk. Confirm club page before treating as current.',
  }),

  // ---------- NHL ----------
  person({
    personKey: 'connor-mcdavid',
    fullName: 'Connor McDavid',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'edmonton-oilers',
    positionOrTitle: 'Center',
    summary: 'Oilers captain and primary elite-skill reference in NHL rankings copy.',
    officialUrl: 'https://www.nhl.com/oilers',
    dataSource: 'NHL.com / Oilers club page',
  }),
  person({
    personKey: 'leon-draisaitl',
    fullName: 'Leon Draisaitl',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'edmonton-oilers',
    positionOrTitle: 'Center/winger',
    summary: 'Oilers co-star in McDavid–Draisaitl duo framing.',
    officialUrl: 'https://www.nhl.com/oilers',
    dataSource: 'NHL.com / Oilers club page',
  }),
  person({
    personKey: 'aleksander-barkov',
    fullName: 'Aleksander Barkov',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Center',
    summary: 'Florida Panthers captain; central to Brad’s disclosed Panthers bias coverage.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'matthew-tkachuk',
    fullName: 'Matthew Tkachuk',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Winger',
    summary: 'Panthers star forward in BB Sports Cup-era coverage.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'auston-matthews',
    fullName: 'Auston Matthews',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'toronto-maple-leafs',
    positionOrTitle: 'Center',
    summary: 'Maple Leafs star referenced in BB Sports Leafs window columns.',
    officialUrl: 'https://www.nhl.com/mapleleafs',
    dataSource: 'NHL.com / Maple Leafs club page',
  }),
  person({
    personKey: 'nathan-mackinnon',
    fullName: 'Nathan MacKinnon',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'colorado-avalanche',
    positionOrTitle: 'Center',
    summary: 'Avalanche star in MacKinnon–Makar core framing.',
    officialUrl: 'https://www.nhl.com/avalanche',
    dataSource: 'NHL.com / Avalanche club page',
  }),
  person({
    personKey: 'cale-makar',
    fullName: 'Cale Makar',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'colorado-avalanche',
    positionOrTitle: 'Defenseman',
    summary: 'Avalanche defenseman in elite-defense franchise notes.',
    officialUrl: 'https://www.nhl.com/avalanche',
    dataSource: 'NHL.com / Avalanche club page',
  }),
  person({
    personKey: 'connor-hellebuyck',
    fullName: 'Connor Hellebuyck',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'winnipeg-jets',
    positionOrTitle: 'Goaltender',
    summary: 'Jets goaltender in Presidents Trophy–era BB Sports notes.',
    officialUrl: 'https://www.nhl.com/jets',
    dataSource: 'NHL.com / Jets club page',
  }),
  person({
    personKey: 'alex-ovechkin',
    fullName: 'Alex Ovechkin',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'washington-capitals',
    positionOrTitle: 'Winger',
    summary: 'Capitals icon in record-chase coverage.',
    officialUrl: 'https://www.nhl.com/capitals',
    dataSource: 'NHL.com / Capitals club page',
  }),
  person({
    personKey: 'sidney-crosby',
    fullName: 'Sidney Crosby',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'pittsburgh-penguins',
    positionOrTitle: 'Center',
    summary: 'Penguins captain in late-window BB Sports framing.',
    officialUrl: 'https://www.nhl.com/penguins',
    dataSource: 'NHL.com / Penguins club page',
  }),
  person({
    personKey: 'kirill-kaprizov',
    fullName: 'Kirill Kaprizov',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'minnesota-wild',
    positionOrTitle: 'Winger',
    summary: 'Wild star in post-cap-hell supporting-cast notes.',
    officialUrl: 'https://www.nhl.com/wild',
    dataSource: 'NHL.com / Wild club page',
  }),

  // ---------- NBA ----------
  person({
    personKey: 'lebron-james',
    fullName: 'LeBron James',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'los-angeles-lakers',
    positionOrTitle: 'Forward',
    summary: 'Lakers franchise figure referenced in BB Sports Lakers criticism.',
    officialUrl: 'https://www.nba.com/lakers',
    dataSource: 'NBA.com / Lakers club page',
  }),
  person({
    personKey: 'stephen-curry',
    fullName: 'Stephen Curry',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'golden-state-warriors',
    positionOrTitle: 'Guard',
    summary: 'Warriors franchise figure central to BB Sports dynasty-era columns.',
    officialUrl: 'https://www.nba.com/warriors',
    dataSource: 'NBA.com / Warriors club page',
  }),
  person({
    personKey: 'nikola-jokic',
    fullName: 'Nikola Jokić',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'denver-nuggets',
    positionOrTitle: 'Center',
    summary: 'Nuggets franchise centerpiece in BB Sports NBA rankings framing.',
    officialUrl: 'https://www.nba.com/nuggets',
    dataSource: 'NBA.com / Nuggets club page',
  }),
  person({
    personKey: 'luka-doncic',
    fullName: 'Luka Dončić',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'los-angeles-lakers',
    positionOrTitle: 'Guard',
    summary:
      'Lakers star after the Mavericks trade window; BB Sports still frames him as a halfcourt-offense centerpiece. Re-verify club page each season.',
    officialUrl: 'https://www.nba.com/lakers',
    dataSource: 'NBA.com / Lakers club page',
    dataConfidence: 'FLAGGED',
    dataNotes:
      'High-profile trade history. Confirm active club association on NBA.com/lakers before treating as current.',
  }),
  person({
    personKey: 'shai-gilgeous-alexander',
    fullName: 'Shai Gilgeous-Alexander',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'oklahoma-city-thunder',
    positionOrTitle: 'Guard',
    summary: 'Thunder star of the young-contender ranking thesis.',
    officialUrl: 'https://www.nba.com/thunder',
    dataSource: 'NBA.com / Thunder club page',
  }),
  person({
    personKey: 'jayson-tatum',
    fullName: 'Jayson Tatum',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'boston-celtics',
    positionOrTitle: 'Forward',
    summary: 'Celtics star in best-roster-construction ranking notes.',
    officialUrl: 'https://www.nba.com/celtics',
    dataSource: 'NBA.com / Celtics club page',
  }),
  person({
    personKey: 'anthony-edwards',
    fullName: 'Anthony Edwards',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'minnesota-timberwolves',
    positionOrTitle: 'Guard',
    summary: 'Timberwolves star in defense-first / double-team offense notes.',
    officialUrl: 'https://www.nba.com/timberwolves',
    dataSource: 'NBA.com / Timberwolves club page',
  }),
  person({
    personKey: 'joel-embiid',
    fullName: 'Joel Embiid',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'philadelphia-76ers',
    positionOrTitle: 'Center',
    summary: '76ers franchise health thesis in BB Sports rankings copy.',
    officialUrl: 'https://www.nba.com/sixers',
    dataSource: 'NBA.com / 76ers club page',
  }),
  person({
    personKey: 'giannis-antetokounmpo',
    fullName: 'Giannis Antetokounmpo',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'milwaukee-bucks',
    positionOrTitle: 'Forward',
    summary: 'Bucks franchise star in ceiling-vs-cap-hell framing.',
    officialUrl: 'https://www.nba.com/bucks',
    dataSource: 'NBA.com / Bucks club page',
  }),
  person({
    personKey: 'victor-wembanyama',
    fullName: 'Victor Wembanyama',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'san-antonio-spurs',
    positionOrTitle: 'Center/forward',
    summary: 'Spurs generational talent in must-watch rebuild notes.',
    officialUrl: 'https://www.nba.com/spurs',
    dataSource: 'NBA.com / Spurs club page',
  }),
  person({
    personKey: 'erik-spoelstra',
    fullName: 'Erik Spoelstra',
    role: 'head_coach',
    leagueKey: 'nba',
    teamKey: 'miami-heat',
    positionOrTitle: 'Head coach',
    summary: 'Long-tenured Heat head coach referenced in BB Sports Heat franchise notes.',
    officialUrl: 'https://www.nba.com/heat',
    dataSource: 'NBA.com / Heat club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'joe-mazulla',
    fullName: 'Joe Mazzulla',
    role: 'head_coach',
    leagueKey: 'nba',
    teamKey: 'boston-celtics',
    positionOrTitle: 'Head coach',
    summary: 'Celtics head coach in championship-roster construction era notes.',
    officialUrl: 'https://www.nba.com/celtics',
    dataSource: 'NBA.com / Celtics club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'ja-morant',
    fullName: 'Ja Morant',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'memphis-grizzlies',
    positionOrTitle: 'Guard',
    summary: 'Grizzlies star in healthy-core top-tier framing.',
    officialUrl: 'https://www.nba.com/grizzlies',
    dataSource: 'NBA.com / Grizzlies club page',
  }),
  person({
    personKey: 'paolo-banchero',
    fullName: 'Paolo Banchero',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'orlando-magic',
    positionOrTitle: 'Forward',
    summary: 'Magic young core figure with Wagner in BB Sports notes.',
    officialUrl: 'https://www.nba.com/magic',
    dataSource: 'NBA.com / Magic club page',
  }),

  // ---------- NFL expansion (coverage depth + Bears bias core) ----------
  person({
    personKey: 'dj-moore',
    fullName: 'D.J. Moore',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Wide receiver',
    summary: 'Bears WR1 material to every BB Sports Bears offense column.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'rome-odunze',
    fullName: 'Rome Odunze',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Wide receiver',
    summary: 'Bears young WR in the Williams–Johnson offense thesis.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'cole-kmet',
    fullName: 'Cole Kmet',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Tight end',
    summary: 'Bears tight end referenced in red-zone and chain-moving notes.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'montez-sweat',
    fullName: 'Montez Sweat',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'Defensive end',
    summary: 'Bears edge rusher in defensive-ceiling framing.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
  }),
  person({
    personKey: 'ryan-poles',
    fullName: 'Ryan Poles',
    role: 'general_manager',
    leagueKey: 'nfl',
    teamKey: 'chicago-bears',
    positionOrTitle: 'General manager',
    summary: 'Bears GM; roster construction is a recurring BB Sports Bears storyline.',
    officialUrl: 'https://www.chicagobears.com/',
    dataSource: 'Chicago Bears official site',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Front-office titles change. Confirm on Bears.com before treating as current.',
  }),
  person({
    personKey: 'saquon-barkley',
    fullName: 'Saquon Barkley',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'philadelphia-eagles',
    positionOrTitle: 'Running back',
    summary: 'Eagles RB and free-agent-to-contender reference in BB Sports NFL copy.',
    officialUrl: 'https://www.philadelphiaeagles.com/',
    dataSource: 'Philadelphia Eagles official site',
  }),
  person({
    personKey: 'nick-sirianni',
    fullName: 'Nick Sirianni',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'philadelphia-eagles',
    positionOrTitle: 'Head coach',
    summary: 'Eagles head coach in championship-window coverage.',
    officialUrl: 'https://www.philadelphiaeagles.com/',
    dataSource: 'Philadelphia Eagles official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'justin-jefferson',
    fullName: 'Justin Jefferson',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'minnesota-vikings',
    positionOrTitle: 'Wide receiver',
    summary: 'Vikings WR superstar and NFC North measuring stick.',
    officialUrl: 'https://www.vikings.com/',
    dataSource: 'Minnesota Vikings official site',
  }),
  person({
    personKey: 'jj-mccarthy',
    fullName: 'J.J. McCarthy',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'minnesota-vikings',
    positionOrTitle: 'Quarterback',
    summary: 'Vikings young QB in NFC North rivalry coverage with the Bears.',
    officialUrl: 'https://www.vikings.com/',
    dataSource: 'Minnesota Vikings official site',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Young QB role can shift with injury and competition. Confirm on Vikings.com.',
  }),
  person({
    personKey: 'amon-ra-st-brown',
    fullName: 'Amon-Ra St. Brown',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'detroit-lions',
    positionOrTitle: 'Wide receiver',
    summary: 'Lions WR and chain-moving identity of the Detroit offense.',
    officialUrl: 'https://www.detroitlions.com/',
    dataSource: 'Detroit Lions official site',
  }),
  person({
    personKey: 'jared-goff',
    fullName: 'Jared Goff',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'detroit-lions',
    positionOrTitle: 'Quarterback',
    summary: 'Lions quarterback in contender-vs-ceiling NFC North framing.',
    officialUrl: 'https://www.detroitlions.com/',
    dataSource: 'Detroit Lions official site',
  }),
  person({
    personKey: 'dan-campbell',
    fullName: 'Dan Campbell',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'detroit-lions',
    positionOrTitle: 'Head coach',
    summary: 'Lions head coach; culture and aggression are BB Sports Lions staples.',
    officialUrl: 'https://www.detroitlions.com/',
    dataSource: 'Detroit Lions official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'brock-purdy',
    fullName: 'Brock Purdy',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'san-francisco-49ers',
    positionOrTitle: 'Quarterback',
    summary: '49ers quarterback in system-QB vs talent-QB arguments.',
    officialUrl: 'https://www.49ers.com/',
    dataSource: 'San Francisco 49ers official site',
  }),
  person({
    personKey: 'christian-mccaffrey',
    fullName: 'Christian McCaffrey',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'san-francisco-49ers',
    positionOrTitle: 'Running back',
    summary: '49ers RB; health is the recurring swing factor in BB Sports notes.',
    officialUrl: 'https://www.49ers.com/',
    dataSource: 'San Francisco 49ers official site',
  }),
  person({
    personKey: 'tyreek-hill',
    fullName: 'Tyreek Hill',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'miami-dolphins',
    positionOrTitle: 'Wide receiver',
    summary: 'Dolphins speed weapon in AFC offense ceiling notes.',
    officialUrl: 'https://www.miamidolphins.com/',
    dataSource: 'Miami Dolphins official site',
  }),
  person({
    personKey: 'tua-tagovailoa',
    fullName: 'Tua Tagovailoa',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'miami-dolphins',
    positionOrTitle: 'Quarterback',
    summary: 'Dolphins QB; durability is the permanent BB Sports subplot.',
    officialUrl: 'https://www.miamidolphins.com/',
    dataSource: 'Miami Dolphins official site',
  }),
  person({
    personKey: 'bo-nix',
    fullName: 'Bo Nix',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'denver-broncos',
    positionOrTitle: 'Quarterback',
    summary: 'Broncos young QB in AFC West climb narratives.',
    officialUrl: 'https://www.denverbroncos.com/',
    dataSource: 'Denver Broncos official site',
  }),
  person({
    personKey: 'drake-maye',
    fullName: 'Drake Maye',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'new-england-patriots',
    positionOrTitle: 'Quarterback',
    summary: 'Patriots franchise-QB project in rebuild coverage.',
    officialUrl: 'https://www.patriots.com/',
    dataSource: 'New England Patriots official site',
  }),
  person({
    personKey: 'myles-garrett',
    fullName: 'Myles Garrett',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'cleveland-browns',
    positionOrTitle: 'Defensive end',
    summary: 'Browns edge star and perennial defensive-MVP conversation piece.',
    officialUrl: 'https://www.clevelandbrowns.com/',
    dataSource: 'Cleveland Browns official site',
  }),
  person({
    personKey: 'travis-kelce',
    fullName: 'Travis Kelce',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'kansas-city-chiefs',
    positionOrTitle: 'Tight end',
    summary: 'Chiefs TE and Mahomes-era championship identity piece.',
    officialUrl: 'https://www.chiefs.com/',
    dataSource: 'Kansas City Chiefs official site',
  }),
  person({
    personKey: 'micah-parsons',
    fullName: 'Micah Parsons',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'dallas-cowboys',
    positionOrTitle: 'Linebacker/edge',
    summary: 'Cowboys defensive star in brand-vs-contention columns. Re-verify club association offseason.',
    officialUrl: 'https://www.dallascowboys.com/',
    dataSource: 'Dallas Cowboys official site',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Trade/contract windows create association risk. Confirm on official club page.',
  }),
  person({
    personKey: 'puka-nacua',
    fullName: 'Puka Nacua',
    role: 'player',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-rams',
    positionOrTitle: 'Wide receiver',
    summary: 'Rams WR in Stafford–McVay skill-talent notes.',
    officialUrl: 'https://www.therams.com/',
    dataSource: 'Los Angeles Rams official site',
  }),
  person({
    personKey: 'brian-daboll',
    fullName: 'Brian Daboll',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'new-york-giants',
    positionOrTitle: 'Head coach',
    summary: 'Giants head coach in NFC East floor/ceiling notes.',
    officialUrl: 'https://www.giants.com/',
    dataSource: 'New York Giants official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'sean-mcvay',
    fullName: 'Sean McVay',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'los-angeles-rams',
    positionOrTitle: 'Head coach',
    summary: 'Rams head coach and modern-offense reference point.',
    officialUrl: 'https://www.therams.com/',
    dataSource: 'Los Angeles Rams official site',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'kyle-shanahan',
    fullName: 'Kyle Shanahan',
    role: 'head_coach',
    leagueKey: 'nfl',
    teamKey: 'san-francisco-49ers',
    positionOrTitle: 'Head coach',
    summary: '49ers head coach; scheme identity is a BB Sports staple.',
    officialUrl: 'https://www.49ers.com/',
    dataSource: 'San Francisco 49ers official site',
    dataConfidence: 'FLAGGED',
  }),

  // ---------- MLB expansion (Cubs bias + league stars) ----------
  person({
    personKey: 'dansby-swanson',
    fullName: 'Dansby Swanson',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Shortstop',
    summary: 'Cubs shortstop and infield anchor in Brad’s disclosed Cubs bias coverage.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
  }),
  person({
    personKey: 'seiya-suzuki',
    fullName: 'Seiya Suzuki',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Outfielder',
    summary: 'Cubs outfielder in middle-of-order offense notes.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
  }),
  person({
    personKey: 'ian-happ',
    fullName: 'Ian Happ',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Outfielder',
    summary: 'Cubs outfielder/switch-hitter regularly cited in North Side columns.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
  }),
  person({
    personKey: 'nico-hoerner',
    fullName: 'Nico Hoerner',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Infielder',
    summary: 'Cubs contact-first infielder in lineup-construction notes.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
  }),
  person({
    personKey: 'craig-counsell',
    fullName: 'Craig Counsell',
    role: 'head_coach',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Manager',
    summary: 'Cubs manager; dugout decisions are fair game in BB Sports baseball takes.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Manager tenures change. Confirm on Cubs club page before treating as current.',
  }),
  person({
    personKey: 'jed-hoyer',
    fullName: 'Jed Hoyer',
    role: 'general_manager',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'President of baseball operations',
    summary: 'Cubs front-office lead in roster-building criticism and praise cycles.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'francisco-lindor',
    fullName: 'Francisco Lindor',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-mets',
    positionOrTitle: 'Shortstop',
    summary: 'Mets shortstop and face of the Cohen-era core.',
    officialUrl: 'https://www.mlb.com/mets',
    dataSource: 'MLB.com / Mets club page',
  }),
  person({
    personKey: 'manny-machado',
    fullName: 'Manny Machado',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'san-diego-padres',
    positionOrTitle: 'Third baseman',
    summary: 'Padres star in payroll-and-contention framing.',
    officialUrl: 'https://www.mlb.com/padres',
    dataSource: 'MLB.com / Padres club page',
  }),
  person({
    personKey: 'fernando-tatis-jr',
    fullName: 'Fernando Tatis Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'san-diego-padres',
    positionOrTitle: 'Outfielder',
    summary: 'Padres superstar talent in must-watch baseball notes.',
    officialUrl: 'https://www.mlb.com/padres',
    dataSource: 'MLB.com / Padres club page',
  }),
  person({
    personKey: 'corbin-carroll',
    fullName: 'Corbin Carroll',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'arizona-diamondbacks',
    positionOrTitle: 'Outfielder',
    summary: 'Diamondbacks young star and speed/power package reference.',
    officialUrl: 'https://www.mlb.com/dbacks',
    dataSource: 'MLB.com / Diamondbacks club page',
  }),
  person({
    personKey: 'julio-rodriguez',
    fullName: 'Julio Rodríguez',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'seattle-mariners',
    positionOrTitle: 'Outfielder',
    summary: 'Mariners franchise face in Pacific Northwest baseball notes.',
    officialUrl: 'https://www.mlb.com/mariners',
    dataSource: 'MLB.com / Mariners club page',
  }),
  person({
    personKey: 'yordan-alvarez',
    fullName: 'Yordan Alvarez',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'houston-astros',
    positionOrTitle: 'Designated hitter/outfielder',
    summary: 'Astros middle-of-order force in AL West coverage.',
    officialUrl: 'https://www.mlb.com/astros',
    dataSource: 'MLB.com / Astros club page',
  }),
  person({
    personKey: 'jose-altuve',
    fullName: 'José Altuve',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'houston-astros',
    positionOrTitle: 'Second baseman',
    summary: 'Astros long-time core and championship-era identity.',
    officialUrl: 'https://www.mlb.com/astros',
    dataSource: 'MLB.com / Astros club page',
  }),
  person({
    personKey: 'bryce-harper',
    fullName: 'Bryce Harper',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'philadelphia-phillies',
    positionOrTitle: 'First baseman/outfielder',
    summary: 'Phillies star and NL East contention face.',
    officialUrl: 'https://www.mlb.com/phillies',
    dataSource: 'MLB.com / Phillies club page',
  }),
  person({
    personKey: 'kyle-tucker',
    fullName: 'Kyle Tucker',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'chicago-cubs',
    positionOrTitle: 'Outfielder',
    summary: 'Cubs outfielder acquisition central to North Side contention talk. Re-verify club association.',
    officialUrl: 'https://www.mlb.com/cubs',
    dataSource: 'MLB.com / Cubs club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'High-profile free-agent/trade movement risk. Confirm club page before treating as current.',
  }),
  person({
    personKey: 'jackson-holliday',
    fullName: 'Jackson Holliday',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'baltimore-orioles',
    positionOrTitle: 'Infielder',
    summary: 'Orioles young-core infielder in cheap-talent-depth coverage.',
    officialUrl: 'https://www.mlb.com/orioles',
    dataSource: 'MLB.com / Orioles club page',
  }),
  person({
    personKey: 'vladimir-guerrero-jr',
    fullName: 'Vladimir Guerrero Jr.',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'toronto-blue-jays',
    positionOrTitle: 'First baseman',
    summary: 'Blue Jays middle-of-order star in AL East notes.',
    officialUrl: 'https://www.mlb.com/bluejays',
    dataSource: 'MLB.com / Blue Jays club page',
  }),
  person({
    personKey: 'gerrit-cole',
    fullName: 'Gerrit Cole',
    role: 'player',
    leagueKey: 'mlb',
    teamKey: 'new-york-yankees',
    positionOrTitle: 'Pitcher',
    summary: 'Yankees ace and payroll-rotation measuring stick. Health is a recurring subplot.',
    officialUrl: 'https://www.mlb.com/yankees',
    dataSource: 'MLB.com / Yankees club page',
  }),

  // ---------- NHL expansion (Panthers bias + contenders) ----------
  person({
    personKey: 'sam-reinhart',
    fullName: 'Sam Reinhart',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Winger',
    summary: 'Panthers goal-scorer in Brad’s disclosed Florida bias Cup-era coverage.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'sam-bennett',
    fullName: 'Sam Bennett',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Center',
    summary: 'Panthers middle-six identity and playoff physicality reference.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'sergei-bobrovsky',
    fullName: 'Sergei Bobrovsky',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Goaltender',
    summary: 'Panthers goaltender; Cup-run reliability is a BB Sports staple.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'gustav-forsling',
    fullName: 'Gustav Forsling',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Defenseman',
    summary: 'Panthers two-way defenseman in defensive-structure notes.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
  }),
  person({
    personKey: 'paul-maurice',
    fullName: 'Paul Maurice',
    role: 'head_coach',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'Head coach',
    summary: 'Panthers head coach of the Cup-era identity. Confirm title each season.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'bill-zito',
    fullName: 'Bill Zito',
    role: 'general_manager',
    leagueKey: 'nhl',
    teamKey: 'florida-panthers',
    positionOrTitle: 'General manager',
    summary: 'Panthers GM; roster construction is central to Florida dynasty talk.',
    officialUrl: 'https://www.nhl.com/panthers',
    dataSource: 'NHL.com / Panthers club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'nikita-kucherov',
    fullName: 'Nikita Kucherov',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'tampa-bay-lightning',
    positionOrTitle: 'Winger',
    summary: 'Lightning star and Atlantic Division measuring stick for Florida.',
    officialUrl: 'https://www.nhl.com/lightning',
    dataSource: 'NHL.com / Lightning club page',
  }),
  person({
    personKey: 'andrei-vasilevskiy',
    fullName: 'Andrei Vasilevskiy',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'tampa-bay-lightning',
    positionOrTitle: 'Goaltender',
    summary: 'Lightning goaltender and elite-netminder reference.',
    officialUrl: 'https://www.nhl.com/lightning',
    dataSource: 'NHL.com / Lightning club page',
  }),
  person({
    personKey: 'david-pastrnak',
    fullName: 'David Pastrňák',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'boston-bruins',
    positionOrTitle: 'Winger',
    summary: 'Bruins sniper in Atlantic contender notes.',
    officialUrl: 'https://www.nhl.com/bruins',
    dataSource: 'NHL.com / Bruins club page',
  }),
  person({
    personKey: 'jack-eichel',
    fullName: 'Jack Eichel',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'vegas-golden-knights',
    positionOrTitle: 'Center',
    summary: 'Golden Knights center and Cup-era Western Conference figure.',
    officialUrl: 'https://www.nhl.com/goldenknights',
    dataSource: 'NHL.com / Golden Knights club page',
  }),
  person({
    personKey: 'artemi-panarin',
    fullName: 'Artemi Panarin',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'new-york-rangers',
    positionOrTitle: 'Winger',
    summary: 'Rangers offensive star in Metropolitan Division coverage.',
    officialUrl: 'https://www.nhl.com/rangers',
    dataSource: 'NHL.com / Rangers club page',
  }),
  person({
    personKey: 'igor-shesterkin',
    fullName: 'Igor Shesterkin',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'new-york-rangers',
    positionOrTitle: 'Goaltender',
    summary: 'Rangers goaltender and elite-netminder conversation piece.',
    officialUrl: 'https://www.nhl.com/rangers',
    dataSource: 'NHL.com / Rangers club page',
  }),
  person({
    personKey: 'sebastian-aho',
    fullName: 'Sebastian Aho',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'carolina-hurricanes',
    positionOrTitle: 'Center',
    summary: 'Hurricanes center and structure-first contender identity.',
    officialUrl: 'https://www.nhl.com/hurricanes',
    dataSource: 'NHL.com / Hurricanes club page',
  }),
  person({
    personKey: 'mikko-rantanen',
    fullName: 'Mikko Rantanen',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'dallas-stars',
    positionOrTitle: 'Winger',
    summary: 'Stars winger after recent club-association change. Re-verify on Stars club page.',
    officialUrl: 'https://www.nhl.com/stars',
    dataSource: 'NHL.com / Stars club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Recent trade window. Confirm active club association before treating as current.',
  }),
  person({
    personKey: 'quinn-hughes',
    fullName: 'Quinn Hughes',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'vancouver-canucks',
    positionOrTitle: 'Defenseman',
    summary: 'Canucks captain/defenseman and Pacific Division face. Re-verify association annually.',
    officialUrl: 'https://www.nhl.com/canucks',
    dataSource: 'NHL.com / Canucks club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'connor-bedard',
    fullName: 'Connor Bedard',
    role: 'player',
    leagueKey: 'nhl',
    teamKey: 'chicago-blackhawks',
    positionOrTitle: 'Center',
    summary: 'Blackhawks franchise centerpiece of the rebuild era.',
    officialUrl: 'https://www.nhl.com/blackhawks',
    dataSource: 'NHL.com / Blackhawks club page',
  }),

  // ---------- NBA expansion (Bulls bias + league faces) ----------
  person({
    personKey: 'coby-white',
    fullName: 'Coby White',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Guard',
    summary: 'Bulls guard and primary scoring engine in Brad’s disclosed Bulls bias coverage.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
  }),
  person({
    personKey: 'nikola-vucevic',
    fullName: 'Nikola Vučević',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Center',
    summary: 'Bulls center and halfcourt offense reference.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
  }),
  person({
    personKey: 'josh-giddey',
    fullName: 'Josh Giddey',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Guard/forward',
    summary: 'Bulls versatile ball-handler in young-core framing.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
  }),
  person({
    personKey: 'patrick-williams',
    fullName: 'Patrick Williams',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Forward',
    summary: 'Bulls forward; development path is a recurring Chicago subplot.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
  }),
  person({
    personKey: 'billy-donovan',
    fullName: 'Billy Donovan',
    role: 'head_coach',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Head coach',
    summary: 'Bulls head coach in culture-and-ceiling notes. Confirm title each season.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'arturas-karnisovas',
    fullName: 'Artūras Karnišovas',
    role: 'executive',
    leagueKey: 'nba',
    teamKey: 'chicago-bulls',
    positionOrTitle: 'Executive vice president of basketball operations',
    summary: 'Bulls front-office lead in roster-construction criticism cycles.',
    officialUrl: 'https://www.nba.com/bulls',
    dataSource: 'NBA.com / Bulls club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'donovan-mitchell',
    fullName: 'Donovan Mitchell',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'cleveland-cavaliers',
    positionOrTitle: 'Guard',
    summary: 'Cavaliers star guard in East contender notes.',
    officialUrl: 'https://www.nba.com/cavaliers',
    dataSource: 'NBA.com / Cavaliers club page',
  }),
  person({
    personKey: 'evan-mobley',
    fullName: 'Evan Mobley',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'cleveland-cavaliers',
    positionOrTitle: 'Forward/center',
    summary: 'Cavaliers two-way big and defensive identity piece.',
    officialUrl: 'https://www.nba.com/cavaliers',
    dataSource: 'NBA.com / Cavaliers club page',
  }),
  person({
    personKey: 'tyrese-haliburton',
    fullName: 'Tyrese Haliburton',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'indiana-pacers',
    positionOrTitle: 'Guard',
    summary: 'Pacers offensive engine in East playoff coverage.',
    officialUrl: 'https://www.nba.com/pacers',
    dataSource: 'NBA.com / Pacers club page',
  }),
  person({
    personKey: 'karl-anthony-towns',
    fullName: 'Karl-Anthony Towns',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'new-york-knicks',
    positionOrTitle: 'Center/forward',
    summary: 'Knicks big after the Timberwolves trade window. Re-verify club association.',
    officialUrl: 'https://www.nba.com/knicks',
    dataSource: 'NBA.com / Knicks club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'jalen-brunson',
    fullName: 'Jalen Brunson',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'new-york-knicks',
    positionOrTitle: 'Guard',
    summary: 'Knicks lead guard and face of the New York contention window.',
    officialUrl: 'https://www.nba.com/knicks',
    dataSource: 'NBA.com / Knicks club page',
  }),
  person({
    personKey: 'anthony-davis',
    fullName: 'Anthony Davis',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'dallas-mavericks',
    positionOrTitle: 'Forward/center',
    summary: 'Mavericks big after Lakers trade window. Health and association are FLAGGED.',
    officialUrl: 'https://www.nba.com/mavericks',
    dataSource: 'NBA.com / Mavericks club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'Trade history and injury risk. Confirm on Mavericks club page before treating as current.',
  }),
  person({
    personKey: 'kyrie-irving',
    fullName: 'Kyrie Irving',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'dallas-mavericks',
    positionOrTitle: 'Guard',
    summary: 'Mavericks guard; availability is the recurring BB Sports subplot.',
    officialUrl: 'https://www.nba.com/mavericks',
    dataSource: 'NBA.com / Mavericks club page',
    dataConfidence: 'FLAGGED',
  }),
  person({
    personKey: 'jamal-murray',
    fullName: 'Jamal Murray',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'denver-nuggets',
    positionOrTitle: 'Guard',
    summary: 'Nuggets co-star next to Jokić in championship-core framing.',
    officialUrl: 'https://www.nba.com/nuggets',
    dataSource: 'NBA.com / Nuggets club page',
  }),
  person({
    personKey: 'bam-adebayo',
    fullName: 'Bam Adebayo',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'miami-heat',
    positionOrTitle: 'Center/forward',
    summary: 'Heat two-way big and Spoelstra-era identity piece.',
    officialUrl: 'https://www.nba.com/heat',
    dataSource: 'NBA.com / Heat club page',
  }),
  person({
    personKey: 'cade-cunningham',
    fullName: 'Cade Cunningham',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'detroit-pistons',
    positionOrTitle: 'Guard',
    summary: 'Pistons franchise guard in young-East rebuild notes.',
    officialUrl: 'https://www.nba.com/pistons',
    dataSource: 'NBA.com / Pistons club page',
  }),
  person({
    personKey: 'devin-booker',
    fullName: 'Devin Booker',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'phoenix-suns',
    positionOrTitle: 'Guard',
    summary: 'Suns star scorer in West contention and payroll notes.',
    officialUrl: 'https://www.nba.com/suns',
    dataSource: 'NBA.com / Suns club page',
  }),
  person({
    personKey: 'kevin-durant',
    fullName: 'Kevin Durant',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'phoenix-suns',
    positionOrTitle: 'Forward',
    summary: 'Suns forward superstar. Re-verify club association each offseason.',
    officialUrl: 'https://www.nba.com/suns',
    dataSource: 'NBA.com / Suns club page',
    dataConfidence: 'FLAGGED',
    dataNotes: 'High free-agent / trade movement risk. Confirm club page before treating as current.',
  }),
  person({
    personKey: 'trae-young',
    fullName: 'Trae Young',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'atlanta-hawks',
    positionOrTitle: 'Guard',
    summary: 'Hawks lead guard and East offensive creativity reference.',
    officialUrl: 'https://www.nba.com/hawks',
    dataSource: 'NBA.com / Hawks club page',
  }),
  person({
    personKey: 'zion-williamson',
    fullName: 'Zion Williamson',
    role: 'player',
    leagueKey: 'nba',
    teamKey: 'new-orleans-pelicans',
    positionOrTitle: 'Forward',
    summary: 'Pelicans star; health is the permanent BB Sports swing variable.',
    officialUrl: 'https://www.nba.com/pelicans',
    dataSource: 'NBA.com / Pelicans club page',
  }),
]);
